#include <stdio.h>
#include "crc.h"

int main()
{
    unsigned long crc_table[256];
    int i;

    make_crc32_table(crc_table);

    printf("/* this file is automatically generated! */\n");
    printf("unsigned long crc_table[256] = {\n ");

    for (i = 0; i < 256; i++) {
        printf(" 0x%08lx,", crc_table[i]);
        if ((i & 15) == 15)
            printf("\n");
        if ((i & 3) == 3)
            printf("\n ");
    }
    printf("};\n");

    return 0;
}
